### ISSUE TITLE
Not Working v1.0

### ISSUE THREAD

**Issue by iHafez** [Strayfade/Lunar#2]
**The UI is bad looking and its only for the sensitivity there's no point of it, also it's slow and doesn't show that it's loading when you press start, the crosshair doesn't move to the player the box detects players but when you aim in nothing happens! fix it please :)**

**Comment by kendinikertenkelebek** [comment]
- It's look designed like 1v1 matches (deathmatch etc...) or single player. detection system detects all players. even our teammates. maybe an option can be added for this.
- head-size-ish target lock maybe usefull (depend on target distance).
- some games use a different coloring for opposing players, like valorant. can be used to improve targeting.
- sometimes targeting some areas of the map. If there really is a neural-network, it can be used for improvement. (wich image targettable or not)

**Comment by Strayfade** [comment]
Fixed a lot of the accuracy and UI issues with 0.3.0. Also, right-click "works" now, check #1 for more info.

**Comment by iHafez** [comment]
yes its working good right now, NIce :)
