### ISSUE TITLE
python 3.8 issue

### ISSUE THREAD

**Issue by kendinikertenkelebek** [Strayfade/Lunar#3]
I've already installed py 3.9.10 and not working. Also 3.8 version is out-dated and not downloadable officily.

Check: [python 3.8.0](https://www.python.org/downloads/release/python-3800/) or [python 3.8.11](https://www.python.org/downloads/release/python-3811/)

Can you integrate for latest or other downloadable versions?

**Comment by iHafez** [comment]
https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64.exe

**Comment by kendinikertenkelebek** [comment]
OK. This is maybe solve this problem but still this is out-dated and need some improvements. Also officially yanked version. The fact that it can still be downloaded somehow is not a permanent solution either. I just point this case.

**Comment by iHafez** [comment]
true

**Comment by Strayfade** [comment]
Python 3.8.0 is downloadable, officially, from the [python.org download page](https://www.python.org/downloads/release/python-380/)
